version: '3'

services:
  django:
    build:
      context: .
      dockerfile: django.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
    command: python manage.py runserver

  react:
    build:
      context: .
      dockerfile: react.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    command: npm start

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
      - react